server:
  port: 9982
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      
spring:
  application:
    name: zuul
    
    
zuul:  routes:    session:
        path: /edu/**
        service-id: eureka-client
        sensitive-headers: Authorization                