spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size:
        10240000
      
    
  mvc:
    view:
      prefix: /
      suffix: .jsp